name: 'Changesets Version and Publish Action'
description: 'Action to check if a changeset was created, helpfull for CI/CD'
author: 'JamilOmar'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'


# Define your outputs here.
outputs:
  hasChangeset:
    description: 'Indicates if a changeset was found'

runs:
  using: node20
  main: dist/index.js
